# Generated by Django 5.0.1 on 2025-10-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarsCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=200)),
                ("germination_on_mars_simulant", models.CharField(max_length=50)),
                ("biomass", models.CharField(max_length=100)),
                ("flowered_seed", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "preferred_ph_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("terrain_soil_texture", models.TextField(blank=True, null=True)),
                (
                    "temperature_range_c",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "humidity_rh_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("moisture_regime", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mars_crops",
                "ordering": ["crop"],
            },
        ),
        migrations.CreateModel(
            name="MarsRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=200)),
                ("latitude_deg", models.CharField(max_length=50)),
                ("longitude_deg", models.CharField(max_length=50)),
                ("elevation_m", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "perchlorate_wt_pct",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "water_release_wt_pct",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ph", models.CharField(blank=True, max_length=50, null=True)),
                ("major_minerals", models.TextField(blank=True, null=True)),
                (
                    "terrain_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mars_regions",
                "ordering": ["region"],
            },
        ),
        migrations.CreateModel(
            name="MarsSite",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("simulator_parameters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mars_sites",
                "ordering": ["name"],
            },
        ),
    ]
